---
- name: Configure Spring Boot Application
  hosts: localhost
  become: yes
  remote_user: ian_escher

  tasks:
    - name: Install Java
      apt:
        update_cache: yes
        name: openjdk-21-jdk
        state: present

#    - name: Install Google Cloud SDK
#      apt:
#        name: google-cloud-sdk
#        state: present

    - name: Create application directory
      file:
        path: /opt/spring-boot-app
        state: directory

    - name: Download Spring Boot application from GCS
      command: gsutil cp gs://tf-portfolio-bucket-iescher/application.jar /opt/spring-boot-app/application.jar

    - name: Create systemd service
      copy:
        dest: /etc/systemd/system/spring-boot.service
        content: |
          [Unit]
          Description=Spring Boot Application
          After=network.target

          [Service]
          ExecStart=/usr/bin/java -jar /opt/spring-boot-app/application.jar
          Restart=always
          User=root
          StandardOutput=syslog
          StandardError=syslog
          SyslogIdentifier=spring-boot

          [Install]
          WantedBy=multi-user.target

    - name: Reload systemd
      systemd:
        daemon_reload: yes
        name: spring-boot
        enabled: yes
        state: started