# Provider config on Google Cloud Platform (GCP)
provider "google" {
  project     = var.gcp_project_id # Project ID
  region      = "europe-west6-a"
  credentials = file("${var.gcp_service_account_key_file_path}") # Define the account service key generated by GCP
}

terraform {
	required_providers {
		google = {
	    version = "~> 6.13.0"
		}
  }
}

