# Provider config on Google Cloud Platform (GCP)
provider "google" {
  project     = var.gcp_project_id # Project ID
  region      = "europe-west6-a"
  credentials = file("${var.gcp_service_account_key_file_path}") # Define the account service key generated by GCP
}

terraform {
	required_providers {
		google = {
	    version = "~> 6.13.0"
		}
  }
}

resource "google_storage_bucket" "portfolio_bucket" {
  name     = var.bucket_name
  location = var.bucket_location
  force_destroy = true

  lifecycle_rule {
    action {
      type = "Delete"
    }
    condition {
      age = 365
    }
  }
}